### ISSUE TITLE
mavros module doesn't start

### ISSUE THREAD

**Issue by fnoop** [goodrobots/maverick-api#215]
modules/base/setup/config.py defines a default for module_deny_list:
```
        define(
            "module_deny_list",
            default=["mavros"],
            type=list,
            help="List of modules to deny loading",
        )
```
However there's no way to unset this.  If you set in the config file:
`module_deny_list = []`
then it fails to start:
```
Mar 03 10:46:19 maverick-ubuntuvm systemd[1]: Started Maverick API Service - dev.
Mar 03 10:46:19 maverick-ubuntuvm api.sh[333]: [I 2020-03-03,10:46:19 /srv/maverick/code/maverick-api/maverick_api/modules/base/setup/logging.py:110]
Mar 03 10:46:19 maverick-ubuntuvm api.sh[333]:     Loaded config options
Mar 03 10:46:19 maverick-ubuntuvm api.sh[333]: [I 2020-03-03,10:46:19 /srv/maverick/code/maverick-api/maverick_api/modules/base/database/__init__.py:12]
Mar 03 10:46:19 maverick-ubuntuvm api.sh[333]:     Database backend seleceted: tinydb
Mar 03 10:46:19 maverick-ubuntuvm api.sh[333]: [I 2020-03-03,10:46:19 /srv/maverick/code/maverick-api/maverick_api/modules/__init__.py:112]
Mar 03 10:46:19 maverick-ubuntuvm api.sh[333]:     Loading module: api.authentication
Mar 03 10:46:19 maverick-ubuntuvm api.sh[333]: [I 2020-03-03,10:46:19 /srv/maverick/code/maverick-api/maverick_api/modules/__init__.py:112]
Mar 03 10:46:19 maverick-ubuntuvm api.sh[333]:     Loading module: api.discovery
Mar 03 10:46:19 maverick-ubuntuvm api.sh[333]: [I 2020-03-03,10:46:19 /srv/maverick/code/maverick-api/maverick_api/modules/__init__.py:112]
Mar 03 10:46:19 maverick-ubuntuvm api.sh[333]:     Loading module: api.maverick
Mar 03 10:46:19 maverick-ubuntuvm api.sh[333]: [W 2020-03-03,10:46:19 /srv/maverick/code/maverick-api/maverick_api/modules/api/maverick/maverick_service.py:82]
Mar 03 10:46:19 maverick-ubuntuvm api.sh[333]:     Could not find service folder at: ~/software/maverick/bin/status.d
Mar 03 10:46:20 maverick-ubuntuvm api.sh[333]: Traceback (most recent call last):
Mar 03 10:46:20 maverick-ubuntuvm api.sh[333]:   File "/srv/maverick/code/maverick-api/maverick-api.py", line 41, in <module>
Mar 03 10:46:20 maverick-ubuntuvm api.sh[333]:     api.initialize()
Mar 03 10:46:20 maverick-ubuntuvm api.sh[333]:   File "/srv/maverick/code/maverick-api/maverick_api/modules/base/apiserver/__init__.py", line 46, in initialize
Mar 03 10:46:20 maverick-ubuntuvm api.sh[333]:     generate_schema()
Mar 03 10:46:20 maverick-ubuntuvm api.sh[333]:   File "/srv/maverick/code/maverick-api/maverick_api/modules/__init__.py", line 110, in generate_schema
Mar 03 10:46:20 maverick-ubuntuvm api.sh[333]:     f"{__name__}.{module_folder_name}.{module_name}"
Mar 03 10:46:20 maverick-ubuntuvm api.sh[333]:   File "/srv/maverick/software/python/lib/python3.7/importlib/__init__.py", line 127, in import_module
Mar 03 10:46:20 maverick-ubuntuvm api.sh[333]:     return _bootstrap._gcd_import(name[level:], package, level)
Mar 03 10:46:20 maverick-ubuntuvm api.sh[333]:   File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
Mar 03 10:46:20 maverick-ubuntuvm api.sh[333]:   File "<frozen importlib._bootstrap>", line 983, in _find_and_load
Mar 03 10:46:20 maverick-ubuntuvm api.sh[333]:   File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
Mar 03 10:46:20 maverick-ubuntuvm api.sh[333]:   File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
Mar 03 10:46:20 maverick-ubuntuvm api.sh[333]:   File "<frozen importlib._bootstrap_external>", line 728, in exec_module
Mar 03 10:46:20 maverick-ubuntuvm api.sh[333]:   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
Mar 03 10:46:20 maverick-ubuntuvm api.sh[333]:   File "/srv/maverick/code/maverick-api/maverick_api/modules/api/mavros/__init__.py", line 16, in <module>
Mar 03 10:46:20 maverick-ubuntuvm api.sh[333]:     from maverick_api.modules.api.mavros.mavros_mission import (
Mar 03 10:46:20 maverick-ubuntuvm api.sh[333]:   File "/srv/maverick/code/maverick-api/maverick_api/modules/api/mavros/mavros_mission.py", line 10, in <module>
Mar 03 10:46:20 maverick-ubuntuvm api.sh[333]:     from modules.api import api_callback, moduleBase, schemaBase
Mar 03 10:46:20 maverick-ubuntuvm api.sh[333]: ModuleNotFoundError: No module named 'modules'
Mar 03 10:46:20 maverick-ubuntuvm systemd[1]: maverick-api@dev.service: Main process exited, code=exited, status=1/FAILURE
Mar 03 10:46:20 maverick-ubuntuvm systemd[1]: maverick-api@dev.service: Failed with result 'exit-code'.
```

**Comment by fnoop** [comment]
Oh wait reading the errors it's the mavros module that's broken, not the lack of modules.

**Comment by fnoop** [comment]
Fixed mavros module imports, fires up now.
