### ISSUE TITLE
Unable to run with python2.7

### ISSUE THREAD

**Issue by SamuelDudley** [goodrobots/maverick-api#3]
```
Traceback (most recent call last):
  File "example_app.py", line 4, in <module>
    from tornadoql.tornadoql import TornadoQL, PORT
  File "/home/mav/tornadoql/tornadoql/tornadoql.py", line 10, in <module>
    from tornadoql.subscription_handler import GQLSubscriptionHandler
  File "/home/mav/tornadoql/tornadoql/subscription_handler.py", line 173
    self.schema, **params, allow_subscriptions=True
                         ^
SyntaxError: invalid syntax
```

**Comment by SamuelDudley** [comment]
fixed with https://github.com/goodrobots/maverick-api/commit/839ad25a946c0f4b3060b43b02661e62232a080b
