### ISSUE TITLE
Arduplane parameters failing to update

### ISSUE THREAD

**Issue by fnoop** [goodrobots/maverick-api#32]
SITL on dev.maverick.one updated to run arduplane.  Params are not failing to update.  error in log:
```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/graphql/execution/executor.py", line 311, in resolve_or_error
    return executor.execute(resolve_fn, source, info, **args)
  File "/usr/local/lib/python2.7/dist-packages/graphql/execution/executors/sync.py", line 7, in execute
    return fn(*args, **kwargs)
  File "/srv/maverick/code/maverick-api/api/schema.py", line 164, in mutate
    ret_val = Parameters.callback(kwargs) # this calls param set
  File "/srv/maverick/code/maverick-api/maverick-api", line 330, in param_set_callback
    ret = param_set(param_data['id'].encode('ascii','ignore'), float(param_data['value']))
  File "/srv/maverick/software/ros/current/lib/python2.7/dist-packages/mavros/param.py", line 146, in param_set
    raise IOError(str(ex))
graphql.error.located_error.GraphQLLocatedError: service [/mavros/param/set] unavailable
```

In tornado.log:
```
2018-03-31 07:09:09,154 DEBUG subscriptions: {u'20': <rx.disposables.anonymousdisposable.AnonymousDisposable object at 0x7fdcda6d2c10>, u'21': <rx.disposables.anonymousdisposable.AnonymousDisposable object at 0x7fdcda6e9090>, u'22': <rx.disposables.anonymousdisposable.AnonymousDisposable object at 0x7fdcdac62ed0>, u'23': <rx.disposables.anonymousdisposable.AnonymousDisposable object at 0x7fdcda679d50>, u'1': <rx.disposables.anonymousdisposable.AnonymousDisposable object at 0x7fdcfa860650>, u'3': <rx.disposables.anonymousdisposable.AnonymousDisposable object at 0x7fdcda7fd410>, u'2': <rx.disposables.anonymousdisposable.AnonymousDisposable object at 0x7fdcda7f4150>, u'5': <rx.disposables.anonymousdisposable.AnonymousDisposable object at 0x7fdcda815410>, u'4': <rx.disposables.anonymousdisposable.AnonymousDisposable object at 0x7fdcda809490>, u'7': <rx.disposables.anonymousdisposable.AnonymousDisposable object at 0x7fdcda78cf50>, u'6': <rx.disposables.anonymousdisposable.AnonymousDisposable object at 0x7fdcda7bba90>, u'9': <rx.disposables.anonymousdisposable.AnonymousDisposable object at 0x7fdcda740650>, u'8': <rx.disposables.anonymousdisposable.AnonymousDisposable object at 0x7fdcda7a7a10>, u'11': <rx.disposables.anonymousdisposable.AnonymousDisposable object at 0x7fdcda740250>, u'10': <rx.disposables.anonymousdisposable.AnonymousDisposable object at 0x7fdcda74d8d0>, u'13': <rx.disposables.anonymousdisposable.AnonymousDisposable object at 0x7fdcda6f49d0>, u'12': <rx.disposables.anonymousdisposable.AnonymousDisposable object at 0x7fdcda765790>, u'15': <rx.disposables.anonymousdisposable.AnonymousDisposable object at 0x7fdcda710910>, u'14': <rx.disposables.anonymousdisposable.AnonymousDisposable object at 0x7fdcda701910>, u'17': <rx.disposables.anonymousdisposable.AnonymousDisposable object at 0x7fdcda729a10>, u'16': <rx.disposables.anonymousdisposable.AnonymousDisposable object at 0x7fdcda71d990>, u'19': <rx.disposables.anonymousdisposable.AnonymousDisposable object at 0x7fdcda6c49d0>, u'18': <rx.disposables.anonymousdisposable.AnonymousDisposable object at 0x7fdcda6b86d0>}
2018-03-31 07:09:48,990 DEBUG graphql request: {u'query': u'mutation updateParam($id: ID, $value: ParamValueType) {\n  updateParam(id: $id, value: $value) {\n    ok\n    param {\n      id\n      value\n      __typename\n    }\n    __typename\n  }\n}\n', u'variables': {u'id': u'AHRS_GPS_USE', u'value': False}, u'operationName': u'updateParam'}
2018-03-31 07:09:49,002 DEBUG GraphQL result data: OrderedDict([(u'updateParam', None)]) errors: [GraphQLLocatedError('service [/mavros/param/set] unavailable',)] invalid False
2018-03-31 07:09:49,002 WARNING GraphQL Error:
2018-03-31 07:09:49,003 DEBUG error_json: {"errors": [{"message": "service [/mavros/param/set] unavailable"}]}
2018-03-31 07:09:49,003 WARNING 400 POST /graphql (127.0.0.1) 14.08ms
```

**Comment by SamuelDudley** [comment]
From the error logs this looks like mavros has failed, so I will start there... I've been out with work and family commitments recently but will be able to review and dev this week after Tuesday.
