### ISSUE TITLE
error when receiving statemessage query/subscription request

### ISSUE THREAD

**Issue by fnoop** [goodrobots/maverick-api#57]
```
2018-12-24,08:19:43.756 INFO close socket <__main__.GraphQLSubscriptionHandler object at 0x7f3a88043be0>
2018-12-24,08:19:43.757 ERROR Exception in callback functools.partial(<function wrap.<locals>.null_wrapper at 0x7f3a94401ea0>, <Task finished coro=<GQLSubscriptionHandler.close_subscriptions() done, defined at /srv/maverick/code/maverick-api/maverick_api/modules/base/tornadoql/subscription_handler.py:148> exception=AttributeError("'ExecutionResult' object has no attribute 'aclose'",)>)
    Traceback (most recent call last):
      File "/srv/maverick/.local/lib/python3.6/site-packages/tornado/ioloop.py", line 758, in _run_callback
        ret = callback()
      File "/srv/maverick/.local/lib/python3.6/site-packages/tornado/stack_context.py", line 300, in null_wrapper
        return fn(*args, **kwargs)
      File "/srv/maverick/.local/lib/python3.6/site-packages/tornado/ioloop.py", line 779, in _discard_future_result
        future.result()
      File "/srv/maverick/code/maverick-api/maverick_api/modules/base/tornadoql/subscription_handler.py", line 151, in close_subscriptions
        await self.subscriptions[sub].dispose()
      File "/srv/maverick/code/maverick-api/maverick_api/modules/base/tornadoql/subscription_handler.py", line 56, in dispose
        await self.subscription.aclose()
    AttributeError: 'ExecutionResult' object has no attribute 'aclose'
2018-12-24,08:19:47.123 INFO open socket <__main__.GraphQLSubscriptionHandler object at 0x7f3a82f88438>
2018-12-24,08:19:47.645 ERROR Exception in callback functools.partial(<function wrap.<locals>.null_wrapper at 0x7f3a82fa7378>, <Task finished coro=<SubscriptionObserver.main() done, defined at /srv/maverick/code/maverick-api/maverick_api/modules/base/tornadoql/subscription_handler.py:42> exception=AttributeError("'ExecutionResult' object has no attribute '__anext__'",)>)
    Traceback (most recent call last):
      File "/srv/maverick/.local/lib/python3.6/site-packages/tornado/ioloop.py", line 758, in _run_callback
        ret = callback()
      File "/srv/maverick/.local/lib/python3.6/site-packages/tornado/stack_context.py", line 300, in null_wrapper
        return fn(*args, **kwargs)
      File "/srv/maverick/.local/lib/python3.6/site-packages/tornado/ioloop.py", line 779, in _discard_future_result
        future.result()
      File "/srv/maverick/code/maverick-api/maverick_api/modules/base/tornadoql/subscription_handler.py", line 46, in main
        result = await self.subscription.__anext__()
    AttributeError: 'ExecutionResult' object has no attribute '__anext__'
```

**Comment by fnoop** [comment]
GraphQLSubscriptionHandler has self.subscribe and also references `from graphql.subscription import subscribe`.  subscription is created from graphql.subscription.subscribe.  Might not be a clash but could be named differently to ensure no clash.

**Comment by SamuelDudley** [comment]
This error occurs when a `ExecutionResult` object gets into the `SubscriptionObserver`.
Fixed in https://github.com/goodrobots/maverick-api/commit/39cc1c60c127419451455c4338d7dda76685344a

**Comment by fnoop** [comment]
This query doesn't work, when it used to:
```
http://dev.maverick.one/web/api/apsitl_py3/graphiql?query=fragment%20StateMessage%20on%20StateMessage%20%7B%0A%20%20id%0A%20%20seq%0A%20%20secs%0A%20%20nsecs%0A%20%20connected%0A%20%20armed%0A%20%20guided%0A%20%20mode%0A%7D%0A%0Asubscription%20stateSubscription%20%7B%0A%20%20StateMessage%20%7B%0A%20%20%20%20...StateMessage%0A%20%20%7D%0A%7D%0A%0A&operationName=stateSubscription
```
Is it because we don't support fragments yet?

**Comment by fnoop** [comment]
This query does work:
http://dev.maverick.one/web/api/apsitl_py3/graphiql?query=subscription%20%7B%0A%20%20StateMessage%20%7B%0A%20%20id%0A%20%20seq%0A%20%20secs%0A%20%20nsecs%0A%20%20connected%0A%20%20armed%0A%20%20guided%0A%20%20mode%0A%7D%0A%7D

**Comment by fnoop** [comment]
Hmm, so a fragment query works:
```
http://dev.maverick.one/web/api/apsitl_py3/graphiql?query=fragment%20Status%20on%20Status%20%7B%0A%20%20id%0A%20%20currentTime%0A%20%20currentStatus%0A%7D%0A%0Aquery%20statusQuery%20%7B%0A%20%20Status%20%7B%0A%20%20%20%20...Status%0A%20%20%7D%0A%7D%0A%0A&operationName=statusQuery
```
And a fragment subscription does as well:
```
http://dev.maverick.one/web/api/apsitl_py3/graphiql?query=fragment%20Status%20on%20Status%20%7B%0A%20%20id%0A%20%20currentTime%0A%20%20currentStatus%0A%7D%0A%0Asubscription%20statusSubscription%20%7B%0A%20%20Status%20%7B%0A%20%20%20%20...Status%0A%20%20%7D%0A%7D%0A%0A%0A&operationName=statusSubscription
```

**Comment by fnoop** [comment]
State Message:
This fragment query works:
http://dev.maverick.one/web/api/apsitl_py3/graphiql?query=fragment%20StateMessage%20on%20StateMessage%20%7B%0A%20%20id%0A%20%20seq%0A%20%20secs%0A%20%20nsecs%0A%20%20connected%0A%20%20armed%0A%20%20guided%0A%20%20mode%0A%7D%0A%0Aquery%20stateQuery%20%7B%0A%20%20StateMessage%20%7B%0A%20%20%20%20...StateMessage%0A%20%20%7D%0A%7D%0A%0A%0A&operationName=stateQuery

Oh, this does work:
http://dev.maverick.one/web/api/apsitl_py3/graphiql?query=fragment%20StateMessage%20on%20StateMessage%20%7B%0A%20%20id%0A%20%20seq%0A%20%20secs%0A%20%20nsecs%0A%20%20connected%0A%20%20armed%0A%20%20guided%0A%20%20mode%0A%7D%0A%0Asubscription%20stateSubscription%20%7B%0A%20%20StateMessage%20%7B%0A%20%20%20%20...StateMessage%0A%20%20%7D%0A%7D%0A%0A%0A%0A&operationName=stateSubscription

**Comment by fnoop** [comment]
Getting constant json errors now, even though the status query/subscription works.
<img width="383" alt="screenshot 2018-12-26 at 08 44 14" src="https://user-images.githubusercontent.com/8210968/50439584-7f24d300-08ea-11e9-87a5-3183477b133f.png">

**Comment by fnoop** [comment]
graphiql btw is very error tolerant - apollo is much less tolerant, it expects perfect answers and schema matching
