### ISSUE TITLE
subscription error

### ISSUE THREAD

**Issue by fnoop** [goodrobots/maverick-api#66]
```
2018-12-26,07:51:39.167 ERROR Uncaught exception GET /graphiql?query=subscription%20%7B%0A%20%20ImuMessage%20%7B%0A%20%20%20%20nsecs%0A%20%20%20%20orientation_x%0A%20%20%20%20orientation_y%0A%20%20%20%20orientation_z%0A%20%20%7D%0A%7D%0A (127.0.0.1)
    HTTPServerRequest(protocol='http', host='dev.maverick.one', method='GET', uri='/graphiql?query=subscription%20%7B%0A%20%20ImuMessage%20%7B%0A%20%20%20%20nsecs%0A%20%20%20%20orientation_x%0A%20%20%20%20orientation_y%0A%20%20%20%20orientation_z%0A%20%20%7D%0A%7D%0A', version='HTTP/1.1', remote_ip='127.0.0.1')
    Traceback (most recent call last):
      File "/srv/maverick/.local/lib/python3.6/site-packages/tornado/web.py", line 1590, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/srv/maverick/code/maverick-api/maverick_api/modules/base/tornadoql/dev_graphiql_handler.py", line 16, in get
        self.finish()
      File "/srv/maverick/.local/lib/python3.6/site-packages/tornado/web.py", line 1022, in finish
        raise RuntimeError("finish() called twice")
    RuntimeError: finish() called twice
```

**Comment by SamuelDudley** [comment]
fixed with https://github.com/goodrobots/maverick-api/commit/da28d68d494728349347a1adaa4f479d8f372ec3
