### ISSUE TITLE
navSatFixed callback error

### ISSUE THREAD

**Issue by fnoop** [goodrobots/maverick-api#8]
```
Feb 09 07:44:22 goodrobots-maverick maverick-api[14616]: [ERROR] [1518162262.001378]: bad callback: <bound method Connection.nav_sat_fix_callback of <__main__.Connection object at 0x7f41918c96d0>>
Feb 09 07:44:22 goodrobots-maverick maverick-api[14616]: Traceback (most recent call last):
Feb 09 07:44:22 goodrobots-maverick maverick-api[14616]:   File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
Feb 09 07:44:22 goodrobots-maverick maverick-api[14616]:     cb(msg)
Feb 09 07:44:22 goodrobots-maverick maverick-api[14616]:   File "/srv/maverick/code/maverick-api/maverick-api", line 214, in nav_sat_fix_callback
Feb 09 07:44:22 goodrobots-maverick maverick-api[14616]:     res = UpdateNavSatFixMessage().mutate(**kwargs)
Feb 09 07:44:22 goodrobots-maverick maverick-api[14616]:   File "/srv/maverick/code/maverick-api/api/schema.py", line 296, in mutate
Feb 09 07:44:22 goodrobots-maverick maverick-api[14616]:     Subscriptions.stream['NavSatFix'].on_next(nav_sat_fixed_message)
Feb 09 07:44:22 goodrobots-maverick maverick-api[14616]:   File "/usr/local/lib/python2.7/dist-packages/rx/subjects/subject.py", line 92, in on_next
Feb 09 07:44:22 goodrobots-maverick maverick-api[14616]:     observer.on_next(value)
Feb 09 07:44:22 goodrobots-maverick maverick-api[14616]:   File "/usr/local/lib/python2.7/dist-packages/rx/core/observerbase.py", line 19, in on_next
Feb 09 07:44:22 goodrobots-maverick maverick-api[14616]:     self._on_next_core(value)
Feb 09 07:44:22 goodrobots-maverick maverick-api[14616]:   File "/usr/local/lib/python2.7/dist-packages/rx/core/autodetachobserver.py", line 16, in _on_next_core
Feb 09 07:44:22 goodrobots-maverick maverick-api[14616]:     self.observer.on_next(value)
Feb 09 07:44:22 goodrobots-maverick maverick-api[14616]:   File "/usr/local/lib/python2.7/dist-packages/rx/core/observerbase.py", line 19, in on_next
Feb 09 07:44:22 goodrobots-maverick maverick-api[14616]:     self._on_next_core(value)
Feb 09 07:44:22 goodrobots-maverick maverick-api[14616]:   File "/usr/local/lib/python2.7/dist-packages/rx/core/anonymousobserver.py", line 14, in _on_next_core
Feb 09 07:44:22 goodrobots-maverick maverick-api[14616]:     self._next(value)
Feb 09 07:44:22 goodrobots-maverick maverick-api[14616]:   File "/usr/local/lib/python2.7/dist-packages/rx/linq/observable/select.py", line 36, in on_next
Feb 09 07:44:22 goodrobots-maverick maverick-api[14616]:     observer.on_next(result)
Feb 09 07:44:22 goodrobots-maverick maverick-api[14616]:   File "/usr/local/lib/python2.7/dist-packages/rx/core/observerbase.py", line 19, in on_next
Feb 09 07:44:22 goodrobots-maverick maverick-api[14616]:     self._on_next_core(value)
Feb 09 07:44:22 goodrobots-maverick maverick-api[14616]:   File "/usr/local/lib/python2.7/dist-packages/rx/core/autodetachobserver.py", line 16, in _on_next_core
Feb 09 07:44:22 goodrobots-maverick maverick-api[14616]:     self.observer.on_next(value)
Feb 09 07:44:22 goodrobots-maverick maverick-api[14616]:   File "/usr/local/lib/python2.7/dist-packages/rx/core/observerbase.py", line 19, in on_next
Feb 09 07:44:22 goodrobots-maverick maverick-api[14616]:     self._on_next_core(value)
Feb 09 07:44:22 goodrobots-maverick maverick-api[14616]:   File "/usr/local/lib/python2.7/dist-packages/rx/core/anonymousobserver.py", line 14, in _on_next_core
Feb 09 07:44:22 goodrobots-maverick maverick-api[14616]:     self._next(value)
Feb 09 07:44:22 goodrobots-maverick maverick-api[14616]:   File "/usr/local/lib/python2.7/dist-packages/rx/core/observerbase.py", line 19, in on_next
Feb 09 07:44:22 goodrobots-maverick maverick-api[14616]:     self._on_next_core(value)
Feb 09 07:44:22 goodrobots-maverick maverick-api[14616]:   File "/usr/local/lib/python2.7/dist-packages/rx/core/autodetachobserver.py", line 16, in _on_next_core
Feb 09 07:44:22 goodrobots-maverick maverick-api[14616]:     self.observer.on_next(value)
Feb 09 07:44:22 goodrobots-maverick maverick-api[14616]:   File "/usr/local/lib/python2.7/dist-packages/rx/core/observerbase.py", line 19, in on_next
Feb 09 07:44:22 goodrobots-maverick maverick-api[14616]:     self._on_next_core(value)
Feb 09 07:44:22 goodrobots-maverick maverick-api[14616]:   File "/usr/local/lib/python2.7/dist-packages/rx/core/anonymousobserver.py", line 14, in _on_next_core
Feb 09 07:44:22 goodrobots-maverick maverick-api[14616]:     self._next(value)
Feb 09 07:44:22 goodrobots-maverick maverick-api[14616]:   File "/usr/local/lib/python2.7/dist-packages/rx/linq/observable/select.py", line 36, in on_next
Feb 09 07:44:22 goodrobots-maverick maverick-api[14616]:     observer.on_next(result)
Feb 09 07:44:22 goodrobots-maverick maverick-api[14616]:   File "/usr/local/lib/python2.7/dist-packages/rx/core/observerbase.py", line 19, in on_next
Feb 09 07:44:22 goodrobots-maverick maverick-api[14616]:     self._on_next_core(value)
Feb 09 07:44:22 goodrobots-maverick maverick-api[14616]:   File "/usr/local/lib/python2.7/dist-packages/rx/core/autodetachobserver.py", line 16, in _on_next_core
Feb 09 07:44:22 goodrobots-maverick maverick-api[14616]:     self.observer.on_next(value)
Feb 09 07:44:22 goodrobots-maverick maverick-api[14616]:   File "/srv/maverick/code/maverick-api/tornadoql/subscription_handler.py", line 39, in on_next
Feb 09 07:44:22 goodrobots-maverick maverick-api[14616]:     self.send_execution_result(self.op_id, value)
Feb 09 07:44:22 goodrobots-maverick maverick-api[14616]:   File "/srv/maverick/code/maverick-api/tornadoql/subscription_handler.py", line 103, in send_execution_result
Feb 09 07:44:22 goodrobots-maverick maverick-api[14616]:     return self.send_message(op_id, GQL_DATA, result)
Feb 09 07:44:22 goodrobots-maverick maverick-api[14616]:   File "/srv/maverick/code/maverick-api/tornadoql/subscription_handler.py", line 80, in send_message
Feb 09 07:44:22 goodrobots-maverick maverick-api[14616]:     return self.write_message(json_message)
Feb 09 07:44:22 goodrobots-maverick maverick-api[14616]:   File "/usr/local/lib/python2.7/dist-packages/tornado/websocket.py", line 252, in write_message
Feb 09 07:44:22 goodrobots-maverick maverick-api[14616]:     return self.ws_connection.write_message(message, binary=binary)
Feb 09 07:44:22 goodrobots-maverick maverick-api[14616]:   File "/usr/local/lib/python2.7/dist-packages/tornado/websocket.py", line 793, in write_message
Feb 09 07:44:22 goodrobots-maverick maverick-api[14616]:     return self._write_frame(True, opcode, message, flags=flags)
Feb 09 07:44:22 goodrobots-maverick maverick-api[14616]:   File "/usr/local/lib/python2.7/dist-packages/tornado/websocket.py", line 776, in _write_frame
Feb 09 07:44:22 goodrobots-maverick maverick-api[14616]:     return self.stream.write(frame)
Feb 09 07:44:22 goodrobots-maverick maverick-api[14616]:   File "/usr/local/lib/python2.7/dist-packages/tornado/iostream.py", line 395, in write
Feb 09 07:44:22 goodrobots-maverick maverick-api[14616]:     self._write_buffer += data
Feb 09 07:44:22 goodrobots-maverick maverick-api[14616]: BufferError: Existing exports of data: object cannot be re-sized
```

**Comment by fnoop** [comment]
Same error for vfr_hud_callback:
```
Feb  9 07:49:59 goodrobots-maverick maverick-api[14616]: [ERROR] [1518162599.931668]: bad callback: <bound method Connection.vfr_hud_callback of <__main__.Connection object at 0x7f41918c96d0>>
Feb  9 07:49:59 goodrobots-maverick maverick-api[14616]: Traceback (most recent call last):
Feb  9 07:49:59 goodrobots-maverick maverick-api[14616]:   File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
Feb  9 07:49:59 goodrobots-maverick maverick-api[14616]:     cb(msg)
```
I can't get subscriptions working at all for these messages in the vue frontend, only for stateMessage.

**Comment by fnoop** [comment]
https://github.com/tornadoweb/tornado/issues/2271
https://github.com/tornadoweb/tornado/pull/2008

**Comment by SamuelDudley** [comment]
This will be fun :S I did see a bit of this occuring during development, at least it is easy to reproduce!

**Comment by SamuelDudley** [comment]
I have a thought to mitigate this issue, but I won't be able to attempt it until Monday evening. Ultimately these need to be asynchronous calls from the main tornado io loop.

**Comment by SamuelDudley** [comment]
problem seems fixed with https://github.com/goodrobots/maverick-api/commit/c73b84b91026b8ca2a256b9595c9daef2a403827

clean up still required

**Comment by fnoop** [comment]
Seems to be working great now :)
